"""Add previous year balance to Miteigentuemer

Revision ID: 31d2927bca31
Revises: 63dbb09c8eed
Create Date: 2025-03-10 12:17:21.039067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d2927bca31'
down_revision = '63dbb09c8eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miteigentuemer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guthaben_vorjahr', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('guthaben_jahr', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miteigentuemer', schema=None) as batch_op:
        batch_op.drop_column('guthaben_jahr')
        batch_op.drop_column('guthaben_vorjahr')

    # ### end Alembic commands ###
