"""Jahresdaten für TOPs und Dokumente

Revision ID: 468c1c7db981
Revises: 31d2927bca31
Create Date: 2025-03-17 22:40:22.676020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468c1c7db981'
down_revision = '31d2927bca31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tagesordnungspunkt_vorlage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jahr', sa.Integer(), nullable=True))

    with op.batch_alter_table('wichtiges_dokument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jahr', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wichtiges_dokument', schema=None) as batch_op:
        batch_op.drop_column('jahr')

    with op.batch_alter_table('tagesordnungspunkt_vorlage', schema=None) as batch_op:
        batch_op.drop_column('jahr')

    # ### end Alembic commands ###
