"""Bankdaten hinzugefügt für miteigentümer

Revision ID: 8159cb2bddee
Revises: c7bf8131e0b3
Create Date: 2025-03-23 15:57:50.487625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8159cb2bddee'
down_revision = 'c7bf8131e0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miteigentuemer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iban', sa.String(length=34), nullable=True))
        batch_op.add_column(sa.Column('bic', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kontoinhaber', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('has_bank_info', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miteigentuemer', schema=None) as batch_op:
        batch_op.drop_column('has_bank_info')
        batch_op.drop_column('kontoinhaber')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('bic')
        batch_op.drop_column('iban')

    # ### end Alembic commands ###
