"""add contact info fields to Miteigentuemer

Revision ID: c7bf8131e0b3
Revises: cebd3d623c59
Create Date: 2025-03-22 18:01:40.797136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7bf8131e0b3'
down_revision = 'cebd3d623c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miteigentuemer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strasse', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('plz', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ort', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telefon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('has_contact_info', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miteigentuemer', schema=None) as batch_op:
        batch_op.drop_column('has_contact_info')
        batch_op.drop_column('email')
        batch_op.drop_column('telefon')
        batch_op.drop_column('ort')
        batch_op.drop_column('plz')
        batch_op.drop_column('strasse')

    # ### end Alembic commands ###
